name: KD Monitor

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * 1-5'

jobs:
  run-kd-monitor:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' 

      # === 這裡是關鍵修正 ===
      - name: Install TA-Lib C-Library (from source)
        run: |
          # 1. 安裝編譯所需的工具
          sudo apt-get update
          sudo apt-get install -y build-essential wget
          
          # 2. 下載 TA-Lib 原始碼
          wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz
          
          # 3. 解壓縮並進入資料夾
          tar -xzf ta-lib-0.4.0-src.tar.gz
          cd ta-lib/
          
          # 4. 編譯並安裝
          ./configure --prefix=/usr
          make
          sudo make install
      # === 修正結束 ===

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run KD Monitor script
        run: |
          python3 stock_monitor.py
        env:
          NTFY_TOPIC: ${{ secrets.NTFY_TOPIC }}
