name: KD Monitor

on:
  # 1. 允許手動觸發 (方便您立刻測試)
  workflow_dispatch:
  
  # 2. 排程觸發
  schedule:
    # 使用 CRON 語法，這是 UTC 時間
    # 台灣時間 (UTC+8) 上午 10:00，等於 UTC 時間 02:00
    # 股市只有週一到週五開盤，所以設 '0 2 * * 1-5'
    - cron: '0 2 * * 1-5'

jobs:
  run-kd-monitor:
    runs-on: ubuntu-latest # 使用 Linux 虛擬機
    
    steps:
      - name: Checkout code
        # 步驟 1: 把您 GitHub 上的程式碼下載到虛擬機
        uses: actions/checkout@v4

      - name: Set up Python
        # 步驟 2: 安裝 Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' 

      - name: Install TA-Lib C-Library
        # 步驟 3: (關鍵！) 安裝 TA-Lib 的 C 語言函式庫
        # (這就是我們在 macOS 上用 brew install ta-lib 做的事)
        run: |
          sudo apt-get update
          sudo apt-get install -y libta-lib0 libta-lib-dev

      - name: Install Python dependencies
        # 步驟 4: 安裝 requirements.txt 裡的所有套件
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run KD Monitor script
        # 步驟 5: 執行您的 Python 腳本
        run: |
          python3 stock_monitor.py
        env:
          # (關鍵！) 將您設定的 GitHub Secret 傳入為環境變數
          NTFY_TOPIC: ${{ secrets.NTFY_TOPIC }}
